---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ascii-{{ .Values.app.version }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ascii
  replicas: {{ .Values.ascii.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ascii
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: ascii
        image: {{ .Values.app.image }}:{{ .Values.app.version }}
        command:
          - ./app
          - "-role"
          - "ascii"
        imagePullPolicy: Always
        env:
          - name: APP_DATASTORE
            value: "{{ .Release.Name }}-data"
          - name: APP_DB_NO_SQL
            value: "{{ .Release.Name }}-db-nosql"
          - name: APP_DB_NO_SQL_PORT
            value: "{{ .Values.db_nosql.port }}"
          - name: APP_DB_SQL
            value: "{{ .Release.Name }}-db-sql"
          - name: APP_DB_SQL_PORT
            value: "{{ .Values.db_sql.port }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.ascii.port }}
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: {{ .Values.ascii.port }}
          initialDelaySeconds: 15
          periodSeconds: 3

