---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datastore-{{ .Values.app.version }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: datastore
      version: {{ .Values.app.version }}
  replicas: {{ .Values.datastore.replicas }}
  template:
    metadata:
      labels:
        app: datastore
        version: {{ .Values.app.version }}
        build: {{ .Values.app.build }}
    spec:
      containers:
      - name: datastore
        image: {{ .Values.app.image }}:{{ .Values.app.version }}-{{ .Values.app.build }}
        env:
          - name: APP_PORT
            value: "80"
          - name: APP_ROLE
            value: "datastore"
          - name: APP_DB
            value: "root@tcp({{ .Release.Name }}-db-sql:{{ .Values.db_sql.port }})/{{ .Release.Name }}"
          - name: APP_DB_NO_SQL
            value: "{{ .Release.Name }}-db-nosql"
          - name: APP_DB_NO_SQL_PORT
            value: "{{ .Values.db_nosql.port }}"
          - name: APP_DB_SQL
            value: "{{ .Release.Name }}-db-sql"
          - name: APP_DB_SQL_PORT
            value: "{{ .Values.db_sql.port }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
