---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Values.app.version }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-data
  replicas: {{ .Values.data.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-data
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: data
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        command:
          - ./app
          - "-role"
          - "data"
          - "-server"
          - {{ .Release.Namespace }}-{{ .Values.nats.service.name }}
        env:
          - name: APP_DB
            value: "root@tcp(db-sql:{{ .Values.db_sql.port }})/demo"
          - name: APP_DB_NO_SQL
            value: "db-nosql"
          - name: APP_DB_NO_SQL_PORT
            value: "{{ .Values.db_nosql.port }}"
          - name: APP_DB_SQL
            value: "db-sql"
          - name: APP_DB_SQL_PORT
            value: "{{ .Values.db_sql.port }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
          name: http
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.data.port }}
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: {{ .Values.data.port }}
          initialDelaySeconds: 15
          periodSeconds: 3
