---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-img
  namespace: {{ .Release.Namespace }}
  labels:
    app: img
  annotations:
    
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: img