---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-img-{{ .Values.app.version }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: img
      version: {{ .Values.app.version }}
  replicas: {{ .Values.img.replicas }}
  template:
    metadata:
      labels:
        app: img
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: img
        image: {{ .Values.app.image }}:{{ .Values.app.version }}
        commnad:
          - app
          - -role img
        imagePullPolicy: Always
        env:
          - name: APP_DATASTORE
            value: "{{ .Release.Name }}-data"
          - name: APP_DB_NO_SQL
            value: "{{ .Release.Name }}-db-nosql"
          - name: APP_DB_NO_SQL_PORT
            value: "{{ .Values.db_nosql.port }}"
          - name: APP_DB_SQL
            value: "{{ .Release.Name }}-db-sql"
          - name: APP_DB_SQL_PORT
            value: "{{ .Values.db_sql.port }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3

