# for versions before 1.9.0 use apps/v1beta2
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      env: prod
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        env: prod
        tier: frontend
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.app.image }}:{{ .Values.app.version }}
        env:
          - name: APP_PORT
            value: {{ .Values.app.port | quote }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.app.port }}
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 3
