# for versions before 1.9.0 use apps/v1beta2
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.app.env }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.app.env }}
  replicas: {{ .Values.app.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.app.env }}
        version: {{ .Values.app.version }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.app.image }}:{{ .Values.app.version }}
        env:
          - name: APP_PORT
            value: {{ .Values.app.port | quote }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: {{ .Values.app.port }}
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
