---
{{- define "canary" }}{{ if gt .Values.app.canary 0.0 }}weight: {{.Values.app.canary}}{{ end }} {{- end }}
{{- define "canary_postfix" }}{{ if gt .Values.app.canary 0.0 }}-canary{{ end }} {{- end }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}{{include "canary_postfix" .}}
  labels:
    app: {{ .Release.Name }}
  annotations:
    {{if contains "front" .Release.Name}}
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-healthz{{include "canary_postfix" .}}
      prefix: /api/
      service: {{ .Release.Name }}{{include "canary_postfix" .}}
      {{include "canary" .}}
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-default{{include "canary_postfix" .}}
      prefix: "/(.*)"
      prefix_regex: true
      service: {{ .Release.Name }}{{include "canary_postfix" .}}
      {{include "canary" .}}
    {{end}}
spec:
  ports:
  - name: http-{{ .Release.Name }}{{include "canary_postfix" .}}
    port: {{ .Values.app.port }}
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Release.Name }}



