apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: db-nosql
  namespace: {{ .Release.Namespace }}
  labels:
    service: db-nosql
spec:
  selector:
    matchLabels:
      app: db-nosql
  replicas: 1
  template:
    metadata:
      labels:
        app: db-nosql
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
