{{- define "prod" }}{{ if gt .Env.PROD "0" }}weight: {{ .Env.PROD }}{{ end }} {{- end }}
{{- define "canary" }}{{ if gt .Env.CANARY "0" }} 
    - destination:
        host: service
        subset: canary
      weight: {{.Env.CANARY}}
{{ end }} {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service
spec:
  hosts:
  - service
  http:
  - route:
    - destination:
        host: service
        subset: prod
      {{template "prod" .}}
      {{template "canary" .}}      
