{{- define "prod" }}{{ if gt .Values.prod 0.0 }}weight: {{.Values.prod}}{{ end }} {{- end }}
{{- define "canary" }}{{ if gt .Values.canary 0.0 }} 
    - destination:
        host: service
        subset: canary
      weight: {{.Values.canary}}
{{ end }} {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service
spec:
  hosts:
  - service
  http:
  - route:
    - destination:
        host: service
        subset: prod
      {{include "prod" .}}
      {{include "canary" .}}      
