app:
  name: k8s-art
  version: v1

image:
  name: denvasyliev/k8s-art
  tag: v1.0.0

api:
  replicas: 1
  canary: 0.0
  header: ""
  port: 8080
  
ascii:
  replicas: 1 
  canary: 0.0
  header: ""
  port: 8080

img:
  replicas: 1 
  canary: 0.0
  header: ""
  port: 8080

ml5:
  replicas: 1 
  canary: 0.0
  header: ""
  port: 8080

data:
  replicas: 1
  port: 8080
  
db_sql:
  port: 3306

db_nosql:
  port: 6379

mq_nats:
  enable: false

ns:
  enable: true

api-gateway:
  image:
    tag: 0.51.0
  service:
    type: LoadBalancer
