app:
  name: k8s-art
  version: v2

image:
  name: denvasyliev/k8s-art
  tag: v2.0.0

api:
  replicas: 1
  canary: 0.0
  header: ""
  port: 8080
  
ascii:
  replicas: 1 
  canary: 0.0
  header: ""
  port: 8080

img:
  replicas: 1 
  canary: 0.0
  header: ""
  port: 8080

ml5:
  replicas: 1 
  canary: 0.0
  header: ""
  port: 8080

data:
  replicas: 1
  port: 8080
  
db_sql:
  port: 3306

db_nosql:
  port: 6379

nats:
  enable: true

ns:
  enable: true

api-gateway:
  image:
    tag: 0.51.2
  service:
    type: NodePort
