---
# Source: demo-app/templates/deployment.yaml
# for versions before 1.9.0 use apps/v1beta2
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: data
spec:
  selector:
    matchLabels:
      app: data
  replicas: 1
  template:
    metadata:
      labels:
        app: data
        version: v0.1.5-56e6f4e
    spec:
      containers:
      - name: data
        image: denvasyliev/data:v0.1.5-56e6f4e
        env:
          - name: APP_PORT
            value: "80"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3

---
# Source: demo-app/templates/service.yaml
---

apiVersion: v1
kind: Service
metadata:
  name: data
  labels:
    app: data
  annotations:
    
spec:
  ports:
  - name: http-data
    port: 80
    targetPort: 80
  selector:
    app: data




