---
# Source: demo-app/templates/deployment.yaml
# for versions before 1.9.0 use apps/v1beta2
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend-v1
spec:
  selector:
    matchLabels:
      app: frontend
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        version: v1
        revision: 0d83836
    spec:
      containers:
      - name: frontend
        image: denvasyliev/k8s-diy:frontend-v1-0d83836
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: "80"
          - name: APP_ROLE
            value: "frontend"
          - name: APP_BACKEND
            value: "backend"
          - name: APP_DATASTORE
            value: "datastore"
          - name: APP_DB
            value: "db"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3




