---
# Source: demo-app/templates/service.yaml
---

apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
  annotations:
    
spec:
  ports:
  - name: http-service
    port: 80
    targetPort: 80
  selector:
    service: front




