---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service
spec:
  hosts:
  - service
  http:
  - route:
    - destination:
        host: service
        subset: v1
      weight: 50
    - destination:
        host: service
        subset: v2
      weight: 50      
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service
spec:
  host: service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2