---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-{{ .Values.backend.version }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: backend
      version: {{ .Values.backend.version }}
  replicas: {{ .Values.backend.replicas }}
  template:
    metadata:
      labels:
        app: backend
        version: {{ .Values.backend.version }}
    spec:
      containers:
      - name: backend
        image: {{ .Values.app.image }}:backend-{{ .Values.backend.version }}-{{ .Values.backend.build }}
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: "80"
          - name: APP_ROLE
            value: "backend"
          - name: APP_DATASTORE
            value: "{{ .Release.Name }}-datastore"
          - name: APP_DB_NO_SQL
            value: "{{ .Release.Name }}-db-nosql"
          - name: APP_DB_NO_SQL_PORT
            value: "{{ .Values.db_nosql.port }}"
          - name: APP_DB_SQL
            value: "{{ .Release.Name }}-db-sql"
          - name: APP_DB_SQL_PORT
            value: "{{ .Values.db_sql.port }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3

