---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-{{ .Values.app.version }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: frontend
      version: {{ .Values.app.version }}
  replicas: {{ .Values.frontend.replicas}}
  template:
    metadata:
      labels:
        app: frontend
        version: {{ .Values.app.version }}
        build: {{ .Values.app.build }}
    spec:
      containers:
      - name: frontend
        image: {{ .Values.app.image }}:{{ .Values.app.version }}-{{ .Values.app.build }}
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: "80"
          - name: APP_ROLE
            value: "frontend"
          - name: APP_BACKEND
            value: "{{ .Release.Name }}-backend"
          - name: APP_DATASTORE
            value: "{{ .Release.Name }}-datastore"
          - name: APP_DB
            value: "{{ .Release.Name }}-db-sql"
          - name: APP_LICENSE
            valueFrom:
              secretKeyRef:
                name: license
                key: license
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
        securityContext:
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readinez
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 3
      volumes:
        - name: data
          configMap:
            name: app-configmap

