---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
    version: v1
  annotations:
    
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-frontend-api-{{ .Values.frontend.version }}
      prefix: /api/
      service: {{ .Release.Name }}-frontend-{{ .Values.frontend.version }}
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Release.Name }}-frontend-default-{{ .Values.frontend.version }}
      prefix: "/(.*)"
      prefix_regex: true
      service: {{ .Release.Name }}-frontend-{{ .Values.frontend.version }}
      
spec:
  ports:
  - name: http-{{ .Release.Name }}-frontend-{{ .Values.frontend.version }}
    port: 80
    targetPort: 80
  selector:
    app: frontend
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
  annotations:
    
spec:
  ports:
  - name: http-{{ .Release.Name }}-backend-{{ .Values.backend.version }}
    port: 80
    targetPort: 80
  selector:
    app: backend

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-datastore
  namespace: {{ .Release.Namespace }}
  labels:
    app: datastore
  annotations: 
    
spec:
  ports:
  - name: http-{{ .Release.Name }}-datastore-{{ .Values.backend.version }}
    port: 80
    targetPort: 80
  selector:
    app: datastore
