name: Continuous Integration

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: "1"
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run linter
       run: make lint
     - name: Run unit tests
       run: make unit-test
     - name: Docker login
       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
     - name: Declare SHA vars to use on other actions
       id: vars
       shell: bash
       run: |
         echo "GITHUB_SHA: ${GITHUB_SHA}"
         echo "::set-output name=sha_short::${GITHUB_SHA::7}"  
     - name: Build Image
       uses: docker/build-push-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: denvasyliev/k8sdiy
         tags: build-${{ steps.vars.outputs.sha_short }}
