name: Continuous Integration

on: [push]

jobs:
  ci:
    name: CI
    runs-on: jess/img:v0.5.7
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run linter
       run: make lint
     - name: Run unit tests
       run: make unit-test
     - name: Build Linux binary
       run: make PLATFORM=linux/amd64